DjangoStuff/TutorialExamples/learning_log/learning_log/urls.py
#from django.conf.urls import include, url #needed only for Django < 1.9
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path('admin/', admin.site.urls),

    #url(r'^users/', include('users.urls', namespace='users')),
    re_path(r'^users/', include('users.urls', namespace='users')),

    #Above line is was already there, followin is added later
    #    according to the text-book instruction (page 413)
    #   May be using url() method is wrong or just a typo. However, the following
    #  forum indicated that above line with path() should be used for the new Django 
    #  versions than the old one with 'url()' and 'include()'. Perhaps this was the
    #  the reason why I failed to sail smoothly last time I tried this example
    # https://stackoverflow.com/questions/44130643/django-admin-urls says:
    #   # In Django 1.9+, you don't need to use include. Use the callable admin.site.urls, not the string 'admin.site.urls'.      url(r'^admin/', admin.site.urls),
    #   # In Django 2.0+, you can use path() instead of url().         path('admin/', admin.site.urls),
    #   # In Django < 1.9 you pass admin.site.urls to include.           url(r'^admin/', include(admin.site.urls)),
    #   # To reverse the admin index url, change the url tag in your template to:       {% url "admin:index" %}
    #
    #url(r'^admin/', include(admin.site.urls)),
    #
    # https://docs.djangoproject.com/en/3.2/topics/http/urls/
    #url(r'', include('learning_logs.urls', namespace='learning_logs')), #old django
    path('',include('learning_logs.urls', namespace='learning_logs'))
]

DjangoStuff/TutorialExamples/learning_log/learning_logs/urls.py
"""Defines URL patterns for learning_logs."""
#from django.conf.urls import url  #old version of Django < 1.9?
#https://stackoverflow.com/questions/44130643/django-admin-urls says:
#https://docs.djangoproject.com/en/3.2/topics/http/urls/
#

#from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = 'learning_logs'

urlpatterns = [
    # Home page
    #url(r'^$', views.index, name='index'),
    #path(r'^$', views.index, name='index'),
    path('', views.index, name='index'),
    #path('', views.IndexView.as_view(), name='index'),

    # Show all topics.
    #url(r'^topics/$', views.topics, name='topics'),
    #path(r'^topics/$', views.topics, name='topics'), #kp: with this the url in the browser 
    #     (when clicked on 'Topics' linked showed up like 'http://127.0.0.1:8000/^topics$/'
    path(r'topics/', views.topics, name='topics'),

    # Detail page for a single topic
    #url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    #path(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'), #To Utilize Regex, we must use re_path() instead
    re_path(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    # Page for adding a new topic
    # url(r'^new_topic/$', views.new_topic, name='new_topic'),
    re_path(r'^new_topic/$', views.new_topic, name='new_topic'),
    # Page for adding a new entry
    re_path(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    # Page for editing an entry
    re_path(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),

]

DjangoStuff/TutorialExamples/learning_log/users/urls.py
"""Defines URL patterns for users"""
#from django.conf.urls import url
from django.urls import include, path, re_path
#from django.contrib.auth.views import login
#https://stackoverflow.com/questions/50669185/python-from-django-contrib-auth-views-import-logout-importerror-cannot-import-n
#from django.contrib.auth import login
from django.contrib.auth.views import LoginView
from . import views

#kp: When I didn't have the app_name added, I got the following error:
#   django.core.exceptions.ImproperlyConfigured: Specifying a namespace in include() without providing an app_name is not supported. Set the app_name attribute in the included module, or pass a 2-tuple containing the list of patterns and app_name instead.
#   So, I googled about it and the following forum rescued me.
#https://stackoverflow.com/questions/48608894/improperlyconfigurederror-about-app-name-when-using-namespace-in-include
app_name = 'users'

urlpatterns = [
    ######### Login page ###########
    #url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    #re_path(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    #kp: Above line gave the following error (when tried to open http://localhost:8000/users/login/):
    #       TypeError: login() got an unexpected keyword argument 'template_name' (seen in the browser tab with above url)
    #    so I googled to get to https://stackoverflow.com/questions/55768131/typeerror-login-got-an-unexpected-keyword-argument-template-name
    #    which led me to use LoginView.as_view() instead of login, ...i.e. above line. And it worked
    re_path(r'^login/$', LoginView.as_view(template_name='users/login.html'), name='login'),

    ########### Logout page ########
    # url(r'^logout/$', views.logout_view, name='logout'),
    re_path(r'^logout/$', views.logout_view, name='logout'),

    ########### Registration page ###############
    #url(r'^register/$', views.register, name='register'),
    re_path(r'^register/$', views.register, name='register'),

]

DjangoStuff/TutorialExamples/learning_log/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    """A topic the user is learning about"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    #owner = models.ForeignKey(User)  #This line gave following error:
    #  TypeError: __init__() missing 1 required positional argument: 'on_delete'
    #  So, I replaced that with the following, and it was okay.
    owner = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text


class Entry(models.Model):
    """Something specific learned about a topic"""
    #topic = models.ForeignKey(Topic) #Showed error
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'entries'
        
    def __str__(self):
        """Return a string representation of the model."""
        return self.text[:50] + "..."

DjangoStuff/TutorialExamples/learning_log/learning_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

    

DjangoStuff/TutorialExamples/learning_log/learning_logs/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
#from django.core.urlresolvers import reverse   #Django 2.0 removes the django.core.urlresolvers module, which was moved to 
# django.urls in version 1.10. https://stackoverflow.com/questions/43139081/importerror-no-module-named-django-core-urlresolvers
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


# Create your views here.
def index(request):
    """The home page for Learning Log"""
    return render(request, 'learning_logs/index.html')

#@login_required is decorator used to restrict access to 'users' data
@login_required  
def topics(request):
    """Show all topics."""
    #topics = Topic.objects.order_by('date_added')
    #Restricting Topics Access to Appropriate Users. Above line doesn't restrict
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')

    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required  
def topic(request, topic_id):
    """Show a single topic and all its entries."""
    #topic = Topic.objects.get(id=topic_id)
    topic = get_object_or_404(Topic, id=topic_id)
    # Make sure the topic belongs to the current user.
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required  
def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(request.POST)
        if form.is_valid():
            #form.save()
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
        
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required  
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))

    #kp: When the following two lines were accidentally indented at the same level as the 'if form.is_valid():', the
    #    server reported errors and I couldn't open the http://127.0.0.1:8000/new_entry/3/ (also saw errors there).
    # The error was as follows:
    #     ValueError: The view learning_logs.views.new_entry didn't return an HttpResponse object. It returned None instead.
    # So, I googled and found this page https://stackoverflow.com/questions/26258905/the-view-didnt-return-an-httpresponse-object-it-returned-none-instead
    # which said Python is very sensitive to indentation and so on. So, fixing the indentation fixed the problem.
    #
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)
    

@login_required  
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    # Following 2 lines for "Protecting the edit_entry Page"
    if topic.owner != request.user:
        raise Http404


    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                                args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

DjangoStuff/TutorialExamples/learning_log/learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Learning Log</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>

  <body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">

	<div class="navbar-header">
	  <button type="button" class="navbar-toggle collapsed"
		  data-toggle="collapse" data-target="#navbar"
		  aria-expanded="false" aria-controls="navbar">
	  </button>
	  <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
            Learning Log</a>
	</div>

	<div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
	    <li><a>Hello, {{ user.username }}.</a></li>
	    <li><a href="{% url 'users:logout' %}">Log Out</a></li>
            {% else %}
	    <li><a href="{% url 'users:register' %}">Register</a></li>
	    <li><a href="{% url 'users:login' %}">Log In</a></li>
            {% endif %}
          </ul>
	</div><!--/.nav-collapse -->
      </div>
    </nav>


    <div class="container">
      <div class="page-header">
	{% block header %}{% endblock header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>

    </div> <!-- /container -->
  </body>
</html>

DjangoStuff/TutorialExamples/learning_log/learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% block content %}
<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
<p>Edit entry:</p>
<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
  {% csrf_token %}
  {{ form.as_p }}
  <button name="submit">save changes</button>
</form>
{% endblock content %}

DjangoStuff/TutorialExamples/learning_log/learning_logs/templates/learning_logs/index.html
<!-- <p>Learning Log</p> -->
<!-- <p>Learning Log helps you keep track of your learning, for any topic you're learning about.</p> -->

<!-- kp: Following child template uses inherittance from base.html -->

{% extends "learning_logs/base.html" %}
{% block header %}
<div class='jumbotron'>
  <h1>Track your learning.</h1>
</div>
{% endblock header %}


{% block content %}
<!-- <p>Learning Log helps you keep track of your learning, for any topic you're learning about.</p> -->
<h2>
  <a href="{% url 'users:register' %}">Register an account</a> to make
  your own Learning Log, and list the topics you're learning about.
</h2>
<h2>Whenever you learn something new about a topic, make an entry summarizing what you've learned.
</h2>

{% endblock content %}

DjangoStuff/TutorialExamples/learning_log/learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% block content %}
<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
<p>Add a new entry:</p>
<form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
  {% csrf_token %}
  {{ form.as_p }}
  <button name='submit'>add entry</button>
</form>
{% endblock content %}
 

DjangoStuff/TutorialExamples/learning_log/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
<h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}

<form action="{% url 'learning_logs:new_topic' %}" method='post' class="form">

  {% csrf_token %}
  {% bootstrap_form form %}

  {% buttons %}
  <button name="submit" class="btn btn-primary">add topic</button>
  {% endbuttons %}

</form>

{% endblock content %}

DjangoStuff/TutorialExamples/learning_log/learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block header %}
<h2>{{ topic }}</h2>
{% endblock header %}


{% block content %}
<p>
  <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
</p>
{% for entry in entries %}
<div class="panel panel-default">
  <div class="panel-heading">
    <h3>
      {{ entry.date_added|date:'M d, Y H:i' }}
      <small>
	<a href="{% url 'learning_logs:edit_entry' entry.id %}"> edit entry</a>
      </small>
    </h3>
  </div>
  <div class="panel-body">
    {{ entry.text|linebreaks }}
  </div>
</div> <!-- panel -->
{% empty %}
There are no entries for this topic yet.
{% endfor %}
{% endblock content %}

DjangoStuff/TutorialExamples/learning_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
<h1>Topics</h1>
{% endblock header %}

{% block content %}

<!-- <p>Topics</p> -->

<ul>
  {% for topic in topics %}
  <!-- <li>{{ topic }}</li>        kp: Here 'topi' has no link-->
  <li>
    <h3>
      <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </h3>
  </li>

  {% empty %}
     <li>No topics have been added yet.</li>
  {% endfor %}
</ul>

<h3> <a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a> </h3>

{% endblock content %}